#
# Makefile for the Linux Wireless network device drivers for Realtek units
#

obj-$(CONFIG_RTL8180)			+= rtl818x/
obj-$(CONFIG_RTL8187)			+= rtl818x/
obj-$(CONFIG_RTLWIFI)			+= rtlwifi/
obj-$(CONFIG_RTL8XXXU)			+= rtl8xxxu/
obj-$(CONFIG_RTL8188EU)			+= rtl8188eus/
obj-$(CONFIG_RTL8814AU)			+= rtl8814au/
obj-$(CONFIG_RTL8812AU)			+= rtl8812au/
obj-$(CONFIG_RTL8192DU)			+= rtl8192du/
obj-$(CONFIG_RTL8723AU)			+= rtl8723au/
obj-$(CONFIG_RTL8723BU)			+= rtl8723bu/
obj-$(CONFIG_RTL8188FU)			+= rtl8188fu/
obj-$(CONFIG_RTL8192EU)			+= rtl8192eu/
